name: Rust Audit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:

  msrv-verify:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.75.0
    - name: Install cargo msrv
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-msrv
    - name: Verify MSRV
      run: cargo msrv verify

  audit:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Run clippy
      run: cargo clippy --verbose --all-targets --all-features -- -D warnings
    - name: Install cargo deny
      uses: taiki-e/install-action@cargo-deny
    - name: Check advisories
      run: cargo deny check advisories
    - name: Check bans
      run: cargo deny check bans